name: Docker image build and push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "30 5 1 * *" # Runs every 1st of the month at 5h30
  workflow_dispatch:

jobs:
  build-and-push:
    # needs: test-build
    runs-on: ubuntu-latest
    name: Build and push ${{ matrix.version }}
    strategy:
      matrix:
        version: ["1"]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push ${{ matrix.version }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./${{ matrix.version }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: hdcore/docker-psscriptanalyzer:${{ matrix.version }}
          cache-from: type=registry,ref=hdcore/docker-psscriptanalyzer:${{ matrix.version }}
          cache-to: type=inline
